CREATE_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS telegram_users
(
ID INTEDER PRIMERI KEY,
TELEGRAM_ID INTEGER,
USERNAME CHAR (50),
FIRST_NAME CHAR (50),
LASTNAME CHAR (50),
UNIQUE (TELEGRAM_ID)
)

"""

INSERT_USER_QUERY = """
INSERT or ignore INTO telegram_users VALUES (?, ?, ?, ?, ?)

"""

CREATE_USER_ANSWERS_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS telegram_users
(
ID INTEDER PRIMERI KEY,
TELEGRAM_ID INTEGER,
USERNAME CHAR (50),
FIRST_NAME CHAR (50),
LASTNAME CHAR (50),
USERS_ANSWER CHAR (50),
UNIQUE (TELEGRAM_ID)
)

"""